# Generated by Django 4.2.6 on 2023-10-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_remove_endereco_instituicao_instituicao_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Formato: (xx) xxxxx-xxxx', max_length=20, verbose_name='Número de Telefone')),
                ('tipo', models.CharField(choices=[('residencial', 'Telefone Residencial'), ('celular', 'Telefone Celular'), ('trabalho', 'Telefone Comercial')], max_length=30, verbose_name='Tipo de Telefone')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.pessoa')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
    ]
