# Generated by Django 4.2.6 on 2023-10-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_parceria_telefone_parceria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.instituicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='parceria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='aplic.parceria'),
            preserve_default=False,
        ),
    ]
