# Generated by Django 4.2.6 on 2023-10-08 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0010_curso_alter_pessoa_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
                ('ano', models.DateField(blank=True, help_text='formato = dd/mm/aaaa', null=True, verbose_name='Data de Início do Projeto')),
                ('periodo_realizacao', models.DateField(blank=True, help_text='formato = dd/mm/aaaa', null=True, verbose_name='Data do Término do Projeto')),
                ('area_atuacao', models.CharField(max_length=100, verbose_name='Área de Atuação')),
                ('resumo', models.TextField(max_length=255, verbose_name='Resumo')),
                ('justificativa', models.TextField(max_length=255, verbose_name='Justificativa')),
                ('fundamentacao_teorica', models.TextField(max_length=255, verbose_name='Fundamentação Teórica')),
                ('metodologia', models.TextField(max_length=255, verbose_name='Metodologia')),
                ('referencia', models.TextField(max_length=255, verbose_name='Referências')),
                ('objetivos_gerais', models.TextField(max_length=255, verbose_name='Objetivos Gerais')),
                ('resultados_esperados', models.TextField(max_length=255, verbose_name='Resultados Esperados')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.instituicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='pessoa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='aplic.pessoa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=30, verbose_name='Nome da Equipe')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.pessoa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.projeto')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
    ]
