# Generated by Django 4.2.6 on 2023-10-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0011_projeto_curso_instituicao_curso_pessoa_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Ods 1', 'ODS 1 - Erradicação da pobreza'), ('Ods 2', 'ODS 2 - Fome zero e agricultura sustentável'), ('Ods 3', 'ODS 3 - Saúde e bem-estar'), ('Ods 4', 'ODS 4 - Educação de qualidade'), ('Ods 5', 'ODS 5 - Igualdade de gênero'), ('Ods 6', 'ODS 6 - Água potável e saneamento'), ('Ods 7', 'ODS 7 - Energia limpa e acessível'), ('Ods 8', 'ODS 8 - Trabalho decente e crescimento econômico'), ('Ods 9', 'ODS 9 - Indústria, inovação e infraestrutura'), ('Ods 10', 'ODS 10 - Redução das desigualdades'), ('Ods 11', 'ODS 11 - Cidades e comunidades sustentáveis'), ('Ods 12', 'ODS 12 - Consumo e produção responsáveis'), ('Ods 13', 'ODS 13 - Ação contra a mudança global do clima'), ('Ods 14', 'ODS 14 - Vida na água'), ('Ods 15', 'ODS 15 - Vida terrestre'), ('Ods 16', 'ODS 16 - Paz, Justiça e Instituições Eficazes'), ('Ods 17', 'ODS 17 - Parcerias e meios de implementação')], max_length=6, verbose_name='Nome da ODS')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'ODS',
                'verbose_name_plural': 'ODSs',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária')),
                ('inicio_atividade', models.DateField(verbose_name='Início da Atividade')),
                ('conclusao_atividade', models.DateField(verbose_name='Conclusão da Atividade')),
                ('objetivo', models.TextField(max_length=255, verbose_name='Objetivo')),
                ('status', models.CharField(choices=[('Realizado', 'Realizado'), ('A Realizar', 'A Realizar'), ('Em Andamento', 'Em Andamento')], max_length=20, verbose_name='Status')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.projeto')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
