# Generated by Django 4.2.6 on 2023-10-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0012_ods_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.atividade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='ods',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='aplic.ods'),
            preserve_default=False,
        ),
    ]
