# Generated by Django 4.2.6 on 2023-10-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0013_remove_atividade_projeto_projeto_atividade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='parceria',
        ),
        migrations.AddField(
            model_name='parceria',
            name='endereco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='aplic.endereco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ods',
            name='descricao',
            field=models.TextField(choices=[('ODS 1 - Erradicação da pobreza', 'O ODS 1 busca eliminar a pobreza em todas as suas formas e em todos os lugares, garantindo que todas as pessoas tenham acesso a recursos básicos e oportunidades para uma vida digna.'), ('ODS 2 - Fome zero e agricultura sustentável', 'O ODS 2  visa acabar com a fome, garantindo o acesso a alimentos seguros e nutritivos para todos, ao mesmo tempo em que promove práticas agrícolas sustentáveis.'), ('ODS 3 - Saúde e bem-estar', 'O ODS 3 concentra-se em assegurar uma vida saudável e promover o bem-estar para todas as idades, com metas que incluem reduzir a mortalidade infantil e melhorar o acesso a serviços de saúde.'), ('ODS 4 - Educação de qualidade', 'O ODS 4 visa garantir uma educação inclusiva, equitativa e de qualidade para todos, promovendo oportunidades de aprendizado ao longo da vida.'), ('ODS 5 - Igualdade de gênero', 'O ODS 5 busca alcançar a igualdade de gênero e empoderar todas as mulheres e meninas, promovendo a igualdade de oportunidades e o fim da discriminação de gênero.'), ('ODS 6 - Água potável e saneamento', 'O ODS 6 visa garantir o acesso universal a água potável segura e saneamento adequado, contribuindo para a saúde e o bem-estar das comunidades.'), ('ODS 7 - Energia limpa e acessível', 'O ODS 7 busca garantir o acesso universal a energia acessível, confiável, sustentável e moderna, promovendo o desenvolvimento econômico e a mitigação das mudanças climáticas.'), ('ODS 8 - Trabalho decente e crescimento econômico', 'O ODS 8 visa promover o crescimento econômico sustentável, emprego digno e produtivo, e trabalho decente para todos.'), ('ODS 9 - Indústria, inovação e infraestrutura', 'O ODS 9 concentra-se na construção de infraestruturas resilientes, na promoção da industrialização sustentável e na inovação tecnológica.'), ('ODS 10 - Redução das desigualdades', 'O ODS 10 busca reduzir as desigualdades dentro e entre os países, promovendo a inclusão social e econômica.'), ('ODS 11 - Cidades e comunidades sustentáveis', 'O ODS 11 visa tornar as cidades e os assentamentos humanos inclusivos, seguros, resilientes e sustentáveis, promovendo uma urbanização planejada.'), ('ODS 12 - Consumo e produção responsáveis', 'O ODS 12 promove padrões de consumo e produção sustentáveis, buscando reduzir o desperdício de recursos naturais e minimizar os impactos ambientais.'), ('ODS 13 - Ação contra a mudança global do clima', 'O ODS 13 visa tomar medidas urgentes para combater as mudanças climáticas e seus impactos, incluindo a mitigação e adaptação.'), ('ODS 14 - Vida na água', 'O ODS 14 se concentra na conservação e uso sustentável dos oceanos, mares e recursos marinhos, para proteger a biodiversidade marinha.'), ('ODS 15 - Vida terrestre', 'O ODS 15 busca proteger, restaurar e promover o uso sustentável dos ecossistemas terrestres, gerenciar de forma sustentável florestas e combater a desertificação.'), ('ODS 16 - Paz, Justiça e Instituições Eficazes', 'O ODS 16 busca promover sociedades pacíficas, justas e inclusivas, fortalecendo as instituições para a promoção da paz e da justiça.'), ('ODS 17 - Parcerias e meios de implementação', 'O ODS 17 é sobre fortalecer os meios de implementação e revitalizar a parceria global para o desenvolvimento sustentável.')], max_length=255, verbose_name='Descrição'),
        ),
    ]
