# Generated by Django 4.2.6 on 2023-10-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0015_alter_telefone_instituicao_alter_telefone_parceria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceria',
            name='nome_parceria',
            field=models.CharField(max_length=100, verbose_name='Nome da Parceria'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.instituicao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telefone',
            name='parceria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.parceria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telefone',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.pessoa'),
            preserve_default=False,
        ),
    ]
