# Generated by Django 4.2.6 on 2023-10-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0016_alter_parceria_nome_parceria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='conclusao_atividade',
            field=models.DateField(null=True, verbose_name='Conclusão da Atividade'),
        ),
    ]
