# Generated by Django 4.2.6 on 2023-10-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0018_alter_atividade_conclusao_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='instituicao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.instituicao'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='parceria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.parceria'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='pessoa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.pessoa'),
        ),
    ]
