# Generated by Django 4.2.6 on 2023-10-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0020_alter_telefone_instituicao_alter_telefone_parceria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='ata_nascimento',
            new_name='data_nascimento',
        ),
    ]
