# Generated by Django 4.2.6 on 2023-10-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0021_rename_ata_nascimento_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=76807, unique=True, verbose_name='Matrícula'),
        ),
    ]
