# Generated by Django 4.2.6 on 2023-10-15 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0022_alter_aluno_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='parceria',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=75929, unique=True, verbose_name='Matrícula'),
        ),
    ]
