# Generated by Django 4.2.6 on 2023-10-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0023_remove_endereco_instituicao_remove_endereco_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=10973, unique=True, verbose_name='Matrícula'),
        ),
    ]
