# Generated by Django 4.2.6 on 2023-10-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0026_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceria',
            name='telefone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=49328, unique=True, verbose_name='Matrícula'),
        ),
    ]
