# Generated by Django 4.2.6 on 2023-10-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0027_parceria_telefone_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=50722, unique=True, verbose_name='Matrícula'),
        ),
    ]
