# Generated by Django 4.2.6 on 2023-10-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0028_alter_aluno_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='instituicao',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=67393, unique=True, verbose_name='Matrícula'),
        ),
    ]
