# Generated by Django 4.2.6 on 2023-10-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0029_remove_curso_instituicao_instituicao_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=77315, unique=True, verbose_name='Matrícula'),
        ),
    ]
