# Generated by Django 4.2.6 on 2023-10-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0033_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.professor'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=70008, unique=True, verbose_name='Matrícula'),
        ),
    ]
