# Generated by Django 4.2.6 on 2023-10-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0034_equipe_professor_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='parceria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.parceria'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=77508, unique=True, verbose_name='Matrícula'),
        ),
    ]
