# Generated by Django 4.2.6 on 2023-10-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0037_alter_aluno_matricula_alter_equipe_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='pessoa',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=43098, unique=True, verbose_name='Matrícula'),
        ),
    ]
