# Generated by Django 4.2.6 on 2023-10-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0038_remove_curso_pessoa_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=71294, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(choices=[('Administração', 'O Bacharelado em Administração busca capacitar os alunos a se adaptarem às necessidades das organizações modernas. O curso promove a criatividade, o raciocínio analítico e o desenvolvimento das habilidades de comunicação. Além disso, enfatiza a integração entre ensino, pesquisa e extensão, proporcionando aos alunos experiências práticas por meio de simuladores empresariais e da empresa júnior Granbery Consultoria.'), ('Sistemas de Informação', 'O Bacharelado em Sistemas de Informação tem como objetivo formar profissionais capazes de implementar, planejar e administrar projetos de software e sistemas de informação. Eles elaboram especificações, verificam a viabilidade técnica e financeira, administram sistemas de informação, prestam consultoria, realizam análises e auditorias, conduzem pesquisas tecnológicas e acompanham o avanço da tecnologia para melhorar a qualidade e produtividade.')], max_length=250, verbose_name='Descrição'),
        ),
    ]
