# Generated by Django 4.2.6 on 2023-10-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0039_alter_aluno_matricula_alter_curso_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=30973, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(choices=[('Administração', 'O Bacharelado em Administração busca capacitar os alunos a se adaptarem às necessidades das organizações modernas. O curso promove a criatividade, o raciocínio analítico e o desenvolvimento das habilidades de comunicação. Além disso, enfatiza a integração entre ensino, pesquisa e extensão, proporcionando aos alunos experiências práticas por meio de simuladores empresariais e da empresa júnior Granbery Consultoria.'), ('Sistemas de Informação', 'O Bacharelado em Sistemas de Informação tem como objetivo formar profissionais capazes de implementar, planejar e administrar projetos de software e sistemas de informação. Eles elaboram especificações, verificam a viabilidade técnica e financeira, administram sistemas de informação, prestam consultoria, realizam análises e auditorias, conduzem pesquisas tecnológicas e acompanham o avanço da tecnologia para melhorar a qualidade e produtividade.'), ('Psicologia', 'O curso de graduação em Psicologia tem como objetivo formar profissionais capacitados tanto como psicólogos quanto como professores de Psicologia. Ele busca fornecer uma formação técnico-científica sólida e estimular uma atuação crítica e criativa na resolução de problemas, levando em consideração diversos aspectos, incluindo ética e humanismo. O curso inclui estágios práticos a partir do terceiro período, preparando os alunos para atuar em várias áreas.'), ('Direito', 'O curso de Direito visa formar profissionais comprometidos com os princípios do Estado Democrático de Direito e dotados de sólidos conhecimentos socio-políticos e éticos. Esses profissionais são incentivados a contribuir para a preservação dos direitos dos cidadãos, uma administração justa da justiça e a transformação da sociedade por meio de uma consciência crítica.'), ('Educação Física', 'O curso de Educação Física tem como objetivo formar profissionais capacitados para atuar na promoção da saúde, do bem-estar e do condicionamento físico das pessoas. Os alunos adquirem conhecimentos sólidos em anatomia, fisiologia, pedagogia, e demais áreas relacionadas à educação física. Além disso, são preparados para desenvolver atividades físicas adaptadas, promovendo inclusão e atendendo a diversos públicos. O curso enfatiza a importância da prática esportiva e da atividade física como ferramentas para melhorar a qualidade de vida das pessoas.')], max_length=30, verbose_name='Descrição'),
        ),
    ]
