# Generated by Django 4.2.5 on 2023-10-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0043_alter_aluno_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='aluno',
            field=models.ManyToManyField(to='aplic.aluno'),
        ),
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.ManyToManyField(to='aplic.professor'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=69308, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(max_length=30, verbose_name='Descrição'),
        ),
    ]
