# Generated by Django 4.2.5 on 2023-10-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0045_alter_aluno_matricula_alter_curso_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='parceria',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='parceria',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='ods',
        ),
        migrations.AddField(
            model_name='aluno',
            name='equipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.equipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='Instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.instituicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.instituicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='parceria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.parceria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ods',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.instituicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='parceria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.parceria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=12826, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='aluno',
            field=models.ManyToManyField(to='aplic.aluno'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='professor',
            field=models.ManyToManyField(to='aplic.professor'),
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='parceria',
        ),
        migrations.AddField(
            model_name='projeto',
            name='parceria',
            field=models.ManyToManyField(to='aplic.parceria'),
        ),
    ]
