# Generated by Django 4.2.5 on 2023-10-17 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0049_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=21369, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='ods',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.projeto'),
        ),
    ]
