# Generated by Django 4.2.5 on 2023-10-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0050_alter_aluno_matricula_alter_ods_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=33504, unique=True, verbose_name='Matrícula'),
        ),
        migrations.RemoveField(
            model_name='ods',
            name='projeto',
        ),
        migrations.AddField(
            model_name='ods',
            name='projeto',
            field=models.ManyToManyField(to='aplic.projeto'),
        ),
    ]
