# Generated by Django 4.2.5 on 2023-10-17 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0051_alter_aluno_matricula_remove_ods_projeto_ods_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=10104, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.professor'),
            preserve_default=False,
        ),
    ]
