# Generated by Django 4.2.5 on 2023-10-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0052_alter_aluno_matricula_alter_equipe_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=91699, unique=True, verbose_name='Matrícula'),
        ),
    ]
