# Generated by Django 4.2.5 on 2023-10-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0055_alter_aluno_matricula_alter_equipe_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ods',
            name='projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='ods',
            field=models.ManyToManyField(to='aplic.ods'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=37165, unique=True, verbose_name='Matrícula'),
        ),
    ]
