# Generated by Django 4.2.5 on 2023-10-17 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0056_remove_ods_projeto_projeto_ods_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='equipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.equipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=39570, unique=True, verbose_name='Matrícula'),
        ),
    ]
