# Generated by Django 4.2.6 on 2023-11-03 15:55

import aplic.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0068_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=aplic.models.get_file_path, variations={'thumb': {'crop': True, 'height': 260, 'width': 420}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=59180, unique=True, verbose_name='Matrícula'),
        ),
    ]
