# Generated by Django 4.2.5 on 2023-11-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0069_curso_imagem_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=62462, unique=True, verbose_name='Matrícula'),
        ),
    ]
