# Generated by Django 4.2.6 on 2023-11-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0081_alter_aluno_matricula_alter_curso_nome_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=93049, unique=True, verbose_name='Matrícula'),
        ),
    ]
