# Generated by Django 4.2.6 on 2023-11-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0082_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=24372, unique=True, verbose_name='Matrícula'),
        ),
    ]
