# Generated by Django 4.2.5 on 2023-11-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0095_alter_aluno_matricula_alter_curso_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=55822, unique=True, verbose_name='Matrícula'),
        ),
    ]
