# Generated by Django 4.2.6 on 2023-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0097_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=37136, unique=True, verbose_name='Matrícula'),
        ),
    ]
