# Generated by Django 4.2.6 on 2023-12-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0098_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=34765, unique=True, verbose_name='Matrícula'),
        ),
    ]
