# Generated by Django 4.2.6 on 2023-12-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0100_curso_texto_alter_aluno_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=78658, unique=True, verbose_name='Matrícula'),
        ),
    ]
