# Generated by Django 4.2.6 on 2023-12-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0101_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=85979, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='texto',
            field=models.TextField(verbose_name='Texto'),
        ),
    ]
